### ISSUE TITLE
Instance check against Axiom type fails

### ISSUE THREAD

**Issue by hsolbrig** [hsolbrig/funowl#33]
```should it be possible to do this?  if isinstance(axiom, Axiom):


(funowl)

  File "/Users/cjm/repos/linkml-owl/tests/test_owl_dumper.py", line 482, in test_owl_dumper
    if isinstance(axiom, Axiom):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 703, in _instancecheck_
    return self.__subclasscheck__(type(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 706, in _subclasscheck_
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```
(From @cmungall )

**Comment by cmungall** [comment]
Sorry didn't have a chance to make a test, but this reproduces:

```python
✗ pipenv run python
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdflib import URIRef
RDFLib Version: 5.0.0
>>> from funowl import SubClassOf, Axiom
>>> ax = SubClassOf(URIRef('http://x.org/x'),URIRef('http://x.org/y'))
>>> ax
SubClassOf(subClassExpression=Class(v='http://x.org/x'), superClassExpression=Class(v='http://x.org/y'), annotations=[])
>>> isinstance(ax, Axiom)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 703, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 706, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```
